const words = [
    { id: "FS0127-01", image: "./img/FS0127/01/blob.png", audio: "./audio/FS0127/01/blob.mp3", english: "blob", korean: "(걸쭉한 액체의) 방울", example: "Here come the blobs!" },
    { id: "FS0127-01", image: "./img/FS0127/01/gift.png", audio: "./audio/FS0127/01/gift.mp3", english: "gift", korean: "선물", example: "They see a gift shop." },
    { id: "FS0127-01", image: "./img/FS0127/01/shop.png", audio: "./audio/FS0127/01/shop.mp3", english: "shop", korean: "상점, 가게", example: "They see a gift shop." },
    { id: "FS0127-01", image: "./img/FS0127/01/gift_shop.png", audio: "./audio/FS0127/01/gift_shop.mp3", english: "gift shop", korean: "선물 가게", example: "They see a gift shop." },
    { id: "FS0127-01", image: "./img/FS0127/01/come.png", audio: "./audio/FS0127/01/come.mp3", english: "come", korean: "(…쪽으로) 오다", example: "Here come the blobs!" },
    { id: "FS0127-01", image: "./img/FS0127/01/see.png", audio: "./audio/FS0127/01/see.mp3", english: "see", korean: "보다", example: "What do they see?" },
    { id: "FS0127-01", image: "./img/FS0127/01/inside.png", audio: "./audio/FS0127/01/inside.mp3", english: "inside", korean: "안에, 안쪽에, 안으로", example: "The blobs go inside." },
    { id: "FS0127-01", image: "./img/FS0127/01/get.png", audio: "./audio/FS0127/01/get.mp3", english: "get", korean: "가지다, 받다, 얻다", example: "They get four T-shirts." },
    { id: "FS0127-01", image: "./img/FS0127/01/tshirt.png", audio: "./audio/FS0127/01/tshirt.mp3", english: "T-shirt", korean: "티셔츠", example: "They get four T-shirts." },
    { id: "FS0127-01", image: "./img/FS0127/01/cap.png", audio: "./audio/FS0127/01/cap.mp3", english: "cap", korean: "모자, 캡", example: "They get four caps." },
    { id: "FS0127-01", image: "./img/FS0127/01/balloon.png", audio: "./audio/FS0127/01/balloon.mp3", english: "balloon", korean: "풍선", example: "They get four balloons." },
    { id: "FS0127-01", image: "./img/FS0127/01/cup.png", audio: "./audio/FS0127/01/cup.mp3", english: "cup", korean: "컵", example: "They get four cups." },
    { id: "FS0127-01", image: "./img/FS0127/01/bag.png", audio: "./audio/FS0127/01/bag.mp3", english: "bag", korean: "가방, 봉지", example: "They get four bags." },
    { id: "FS0127-01", image: "./img/FS0127/01/only.png", audio: "./audio/FS0127/01/only.mp3", english: "only", korean: "단지, 오직", example: "But there are only three blobs." },
    { id: "FS0127-01", image: "./img/FS0127/01/teddy_bear.png", audio: "./audio/FS0127/01/teddy_bear.mp3", english: "teddy bear", korean: "테디 베어, 곰 인형", example: "They get a teddy bear!" },
    { id: "FS0127-01", image: "./img/FS0127/01/take_a_picture.png", audio: "./audio/FS0127/01/take_a_picture.mp3", english: "take a picture", korean: "사진을 찍다", example: "They take a picture!" },
    { id: "FS0127-01", image: "./img/FS0127/01/silly.png", audio: "./audio/FS0127/01/silly.mp3", english: "silly", korean: "우스꽝스러운, 유치한", example: "Silly blobs!" },
    { id: "FS0127-01", image: "./img/FS0127/01/good_bye.png", audio: "./audio/FS0127/01/good_bye.mp3", english: "good-bye", korean: "안녕, 안녕히 계세요 (헤어질 때 하는 인사)", example: "Good-bye!" },
    { id: "FS0127-01", image: "./img/FS0127/01/click.png", audio: "./audio/FS0127/01/click.mp3", english: "Click!", korean: "(찰칵) 사진 찍는 소리", example: "Click! They take a picture!" },
    { id: "FS0127-01", image: "./img/FS0127/01/picture.png", audio: "./audio/FS0127/01/picture.mp3", english: "picture", korean: "사진, 그림", example: "They take a picture!" },
    { id: "FS0127-02", image: "./img/FS0127/02/blob.png", audio: "./audio/FS0127/02/blob.mp3", english: "blob", korean: "(걸쭉한 액체의) 방울·덩어리", example: "Here come the blobs!" },
    { id: "FS0127-02", image: "./img/FS0127/02/bumper.png", audio: "./audio/FS0127/02/bumper.mp3", english: "bumper", korean: "(자동차의) 범퍼", example: "They see bumper cars!" },
    { id: "FS0127-02", image: "./img/FS0127/02/bumper_car.png", audio: "./audio/FS0127/02/bumper_car.mp3", english: "bumper car", korean: "범퍼카(놀이기구)", example: "They see bumper cars!" },
    { id: "FS0127-02", image: "./img/FS0127/02/get_into.png", audio: "./audio/FS0127/02/get_into.mp3", english: "get into", korean: "…에 들어가다, 타다", example: "The blobs get into a car." },
    { id: "FS0127-02", image: "./img/FS0127/02/forward.png", audio: "./audio/FS0127/02/forward.mp3", english: "forward", korean: "앞으로", example: "The bumper car goes forward." },
    { id: "FS0127-02", image: "./img/FS0127/02/bump.png", audio: "./audio/FS0127/02/bump.mp3", english: "bump", korean: "쿵! (부딪치는 소리)", example: "Bump!" },
    { id: "FS0127-02", image: "./img/FS0127/02/backward.png", audio: "./audio/FS0127/02/backward.mp3", english: "backward", korean: "뒤로", example: "The car goes backward." },
    { id: "FS0127-02", image: "./img/FS0127/02/left.png", audio: "./audio/FS0127/02/left.mp3", english: "left", korean: "왼쪽으로", example: "The car goes left." },
    { id: "FS0127-02", image: "./img/FS0127/02/right.png", audio: "./audio/FS0127/02/right.mp3", english: "right", korean: "오른쪽으로", example: "The car goes right." },
    { id: "FS0127-02", image: "./img/FS0127/02/slow.png", audio: "./audio/FS0127/02/slow.mp3", english: "slow", korean: "느리게", example: "The car goes slow." },
    { id: "FS0127-02", image: "./img/FS0127/02/fast.png", audio: "./audio/FS0127/02/fast.mp3", english: "fast", korean: "빠르게", example: "The car goes fast." },
    { id: "FS0127-02", image: "./img/FS0127/02/really.png", audio: "./audio/FS0127/02/really.mp3", english: "really", korean: "정말로", example: "The car goes really fast!" },
    { id: "FS0127-02", image: "./img/FS0127/02/vroom.png", audio: "./audio/FS0127/02/vroom.mp3", english: "Vroom!", korean: "부르릉!", example: "Vroom!" },
    { id: "FS0127-02", image: "./img/FS0127/02/silly.png", audio: "./audio/FS0127/02/silly.mp3", english: "silly", korean: "우스꽝스러운, 유치한", example: "Silly!" },
    { id: "FS0127-02", image: "./img/FS0127/02/car.png", audio: "./audio/FS0127/02/car.mp3", english: "car", korean: "자동차", example: "The blobs get into a car." },
    { id: "FS0127-03", image: "./img/FS0127/03/blob.png", audio: "./audio/FS0127/03/blob.mp3", english: "blob", korean: "(둥글한) 덩어리, 블롭", example: "Here come the blobs!" },
    { id: "FS0127-03", image: "./img/FS0127/03/merry_go_round.png", audio: "./audio/FS0127/03/merry_go_round.mp3", english: "merry-go-round", korean: "회전목마", example: "They see a merry-go-round!" },
    { id: "FS0127-03", image: "./img/FS0127/03/go_up_to.png", audio: "./audio/FS0127/03/go_up_to.mp3", english: "go up to", korean: "…에게/…쪽으로 다가가다", example: "The blobs go up to the merry-go-round." },
    { id: "FS0127-03", image: "./img/FS0127/03/horse.png", audio: "./audio/FS0127/03/horse.mp3", english: "horse", korean: "말", example: "There’s a horse." },
    { id: "FS0127-03", image: "./img/FS0127/03/donkey.png", audio: "./audio/FS0127/03/donkey.mp3", english: "donkey", korean: "당나귀", example: "There’s a donkey." },
    { id: "FS0127-03", image: "./img/FS0127/03/giraffe.png", audio: "./audio/FS0127/03/giraffe.mp3", english: "giraffe", korean: "기린", example: "There’s a giraffe." },
    { id: "FS0127-03", image: "./img/FS0127/03/zebra.png", audio: "./audio/FS0127/03/zebra.mp3", english: "zebra", korean: "얼룩말", example: "There’s a zebra." },
    { id: "FS0127-03", image: "./img/FS0127/03/elephant.png", audio: "./audio/FS0127/03/elephant.mp3", english: "elephant", korean: "코끼리", example: "There’s an elephant." },
    { id: "0003", image: "./img/FS0127/03/whats_wrong.png", audio: "./audio/FS0127/03/whats_wrong.mp3", english: "what’s wrong?", korean: "무슨 일이야? 왜 그래?", example: "Blobs, what’s wrong?" },
    { id: "FS0127-03", image: "./img/FS0127/03/scary.png", audio: "./audio/FS0127/03/scary.mp3", english: "scary", korean: "무서운", example: "There’s a scary lion!" },
    { id: "FS0127-03", image: "./img/FS0127/03/lion.png", audio: "./audio/FS0127/03/lion.mp3", english: "lion", korean: "사자", example: "There’s a scary lion!" },
    { id: "FS0127-03", image: "./img/FS0127/03/run.png", audio: "./audio/FS0127/03/run.mp3", english: "run", korean: "달리다", example: "The blobs run." },
    { id: "FS0127-03", image: "./img/FS0127/03/whew.png", audio: "./audio/FS0127/03/whew.mp3", english: "whew", korean: "휴~, 살았다", example: "Whew, the lion is gone." },
    { id: "FS0127-03", image: "./img/FS0127/03/gone.png", audio: "./audio/FS0127/03/gone.mp3", english: "gone", korean: "사라진, 없는", example: "The lion is gone." },
    { id: "FS0127-03", image: "./img/FS0127/03/back.png", audio: "./audio/FS0127/03/back.mp3", english: "back", korean: "돌아와서", example: "Oh no! The lion’s back!" },
    { id: "FS0127-03", image: "./img/FS0127/03/silly.png", audio: "./audio/FS0127/03/silly.mp3", english: "silly", korean: "우스꽝스러운, 유치한", example: "Silly blobs!" },


    { id: "wonbuk-01", image: "./img/wonbuk/01/clean.png", audio: "./audio/wonbuk/01/clean.mp3", english: "clean", korean: "깨끗한, 청소하다", example: "My room is clean." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/wonderful.png", audio: "./audio/wonbuk/01/wonderful.mp3", english: "wonderful", korean: "멋진, 훌륭한, 놀라운", example: "The cake is wonderful." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/home.png", audio: "./audio/wonbuk/01/home.mp3", english: "home", korean: "집, 가정", example: "I go home after school." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/angry.png", audio: "./audio/wonbuk/01/angry.mp3", english: "angry", korean: "화난, 성난", example: "He is angry." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/really.png", audio: "./audio/wonbuk/01/really.mp3", english: "really", korean: "정말, 사실상, 실제로", example: "I really like pizza." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/well.png", audio: "./audio/wonbuk/01/well.mp3", english: "well", korean: "잘, 충분히, 우물", example: "She swims well." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/middle.png", audio: "./audio/wonbuk/01/middle.mp3", english: "middle", korean: "중앙의, 중간의", example: "Put the ball in the middle." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/tall.png", audio: "./audio/wonbuk/01/tall.mp3", english: "tall", korean: "키가 큰, 높은", example: "The tree is tall." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/every.png", audio: "./audio/wonbuk/01/every.mp3", english: "every", korean: "모든, 모두", example: "I read every day." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/long.png", audio: "./audio/wonbuk/01/long.mp3", english: "long", korean: "긴, 오래, 오랫동안", example: "The river is long." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/short.png", audio: "./audio/wonbuk/02/short.mp3", english: "short", korean: "짧은, 단기의, 작은", example: "My hair is short." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/straight.png", audio: "./audio/wonbuk/02/straight.mp3", english: "straight", korean: "똑바로, 직선, 바로", example: "Draw a straight line." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/ahead.png", audio: "./audio/wonbuk/02/ahead.mp3", english: "ahead", korean: "앞서, 앞에, 미리", example: "Walk ahead." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/busy.png", audio: "./audio/wonbuk/02/busy.mp3", english: "busy", korean: "바쁜, 분주한", example: "Dad is busy." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/full.png", audio: "./audio/wonbuk/02/full.mp3", english: "full", korean: "가득한, 완전한", example: "The box is full." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/more.png", audio: "./audio/wonbuk/02/more.mp3", english: "more", korean: "더 많은, 더욱", example: "I want more juice." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/ready.png", audio: "./audio/wonbuk/02/ready.mp3", english: "ready", korean: "준비된, 사전에", example: "Are you ready?" },
    { id: "wonbuk-02", image: "./img/wonbuk/02/some.png", audio: "./audio/wonbuk/02/some.mp3", english: "some", korean: "몇몇, 일부, ~중에는", example: "I have some books." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/today.png", audio: "./audio/wonbuk/02/today.mp3", english: "today", korean: "오늘, 현재, 지금", example: "It is hot today." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/favorite.png", audio: "./audio/wonbuk/02/favorite.mp3", english: "favorite", korean: "가장 좋아하는, 마음에 드는", example: "Pizza is my favorite food." },
    { id: "wonbuk-03", image: "./img/wonbuk/03/song.png", audio: "./audio/wonbuk/03/song.mp3", english: "song", korean: "노래, 곡", example: "I like this song." },
    { id: "wonbuk-03", image: "./img/wonbuk/03/we.png", audio: "./audio/wonbuk/03/we.mp3", english: "we", korean: "우리", example: "We are best friends." },
    { id: "wonbuk-03", image: "./img/wonbuk/03/ball.png", audio: "./audio/wonbuk/03/ball.mp3", english: "ball", korean: "공, 볼", example: "The ball is under the table." },
    { id: "wonbuk-03", image: "./img/wonbuk/03/bank.png", audio: "./audio/wonbuk/03/bank.mp3", english: "bank", korean: "은행, 강둑", example: "Let’s go to the bank." },
    { id: "wonbuk-03", image: "./img/wonbuk/03/shopping.png", audio: "./audio/wonbuk/03/shopping.mp3", english: "shopping", korean: "쇼핑, 가게 구경", example: "Mom is shopping for clothes." },
    { id: "wonbuk-03", image: "./img/wonbuk/03/together.png", audio: "./audio/wonbuk/03/together.mp3", english: "together", korean: "함께, 같이, 서로", example: "Let’s play together." },
    { id: "wonbuk-03", image: "./img/wonbuk/03/stay.png", audio: "./audio/wonbuk/03/stay.mp3", english: "stay", korean: "머물다, 지내다", example: "Please stay here." },
    { id: "wonbuk-03", image: "./img/wonbuk/03/again.png", audio: "./audio/wonbuk/03/again.mp3", english: "again", korean: "한 번 더, 다시", example: "Try it again." },
    { id: "wonbuk-03", image: "./img/wonbuk/03/city.png", audio: "./audio/wonbuk/03/city.mp3", english: "city", korean: "도시, 시내, 도심", example: "I live in a big city." },
    { id: "wonbuk-03", image: "./img/wonbuk/03/fun.png", audio: "./audio/wonbuk/03/fun.mp3", english: "fun", korean: "재미있는, 즐거운", example: "This game is so fun!" },
    { id: "wonbuk-04", image: "./img/wonbuk/04/with.png", audio: "./audio/wonbuk/04/with.mp3", english: "with", korean: "함께", example: "I went to the park with my friend." },
    { id: "wonbuk-04", image: "./img/wonbuk/04/living.png", audio: "./audio/wonbuk/04/living.mp3", english: "living", korean: "살아 있는, 생활의", example: "There are many living plants in the garden." },
    { id: "wonbuk-04", image: "./img/wonbuk/04/yesterday.png", audio: "./audio/wonbuk/04/yesterday.mp3", english: "yesterday", korean: "어제", example: "I met him yesterday." },
    { id: "wonbuk-04", image: "./img/wonbuk/04/everywhere.png", audio: "./audio/wonbuk/04/everywhere.mp3", english: "everywhere", korean: "어디나", example: "Flowers are blooming everywhere." },
    { id: "wonbuk-04", image: "./img/wonbuk/04/free.png", audio: "./audio/wonbuk/04/free.mp3", english: "free", korean: "자유의, 무료의", example: "The museum is free on Sundays." },
    { id: "wonbuk-04", image: "./img/wonbuk/04/about.png", audio: "./audio/wonbuk/04/about.mp3", english: "about", korean: "~에 대하여", example: "This book is about animals." },
    { id: "wonbuk-04", image: "./img/wonbuk/04/from.png", audio: "./audio/wonbuk/04/from.mp3", english: "from", korean: "~로부터, ~에서", example: "I got a letter from my cousin." },
    { id: "wonbuk-04", image: "./img/wonbuk/04/over.png", audio: "./audio/wonbuk/04/over.mp3", english: "over", korean: "~이상, 위의", example: "The plane is flying over the city." },
    { id: "wonbuk-04", image: "./img/wonbuk/04/under.png", audio: "./audio/wonbuk/04/under.mp3", english: "under", korean: "아래의, ~ 밑에", example: "The cat is hiding under the bed." },
    { id: "wonbuk-04", image: "./img/wonbuk/04/art.png", audio: "./audio/wonbuk/04/art.mp3", english: "art", korean: "예술, 미술, 아트", example: "She loves modern art." },
    { id: "wonbuk-05", image: "./img/wonbuk/05/bookcase.png", audio: "./audio/wonbuk/05/bookcase.mp3", english: "bookcase", korean: "책장", example: "The bookcase is full of books." },
    { id: "wonbuk-05", image: "./img/wonbuk/05/box.png", audio: "./audio/wonbuk/05/box.mp3", english: "box", korean: "상자, 박스", example: "There is a toy in the box." },
    { id: "wonbuk-05", image: "./img/wonbuk/05/egg.png", audio: "./audio/wonbuk/05/egg.mp3", english: "egg", korean: "달걀, 알, 계란", example: "I had a boiled egg for breakfast." },
    { id: "wonbuk-05", image: "./img/wonbuk/05/fine.png", audio: "./audio/wonbuk/05/fine.mp3", english: "fine", korean: "좋은, 벌금, 미세한", example: "The weather is fine today." },
    { id: "wonbuk-05", image: "./img/wonbuk/05/goat.png", audio: "./audio/wonbuk/05/goat.mp3", english: "goat", korean: "염소", example: "The goat is eating grass." },
    { id: "wonbuk-05", image: "./img/wonbuk/05/headache.png", audio: "./audio/wonbuk/05/headache.mp3", english: "headache", korean: "두통, 골칫거리", example: "I have a headache." },
    { id: "wonbuk-05", image: "./img/wonbuk/05/music.png", audio: "./audio/wonbuk/05/music.mp3", english: "music", korean: "음악, 노래", example: "I like listening to music." },
    { id: "wonbuk-05", image: "./img/wonbuk/05/prince.png", audio: "./audio/wonbuk/05/prince.mp3", english: "prince", korean: "왕자, 세자, 프린스", example: "The prince lives in a big castle." },
    { id: "wonbuk-05", image: "./img/wonbuk/05/science.png", audio: "./audio/wonbuk/05/science.mp3", english: "science", korean: "과학, 사이언스", example: "Science is my favorite subject." },
    { id: "wonbuk-05", image: "./img/wonbuk/05/way.png", audio: "./audio/wonbuk/05/way.mp3", english: "way", korean: "방법, 길, 방식", example: "This is the best way to school." },
    { id: "wonbuk-06", image: "./img/wonbuk/06/boat.png", audio: "./audio/wonbuk/06/boat.mp3", english: "boat", korean: "배, 보트", example: "We went fishing on a boat." },
    { id: "wonbuk-06", image: "./img/wonbuk/06/chopstick.png", audio: "./audio/wonbuk/06/chopstick.mp3", english: "chopstick", korean: "젓가락", example: "I can eat with chopsticks." },
    { id: "wonbuk-06", image: "./img/wonbuk/06/glue.png", audio: "./audio/wonbuk/06/glue.mp3", english: "glue", korean: "풀, 접착제, 붙이다", example: "Use glue to fix the broken toy." },
    { id: "wonbuk-06", image: "./img/wonbuk/06/try.png", audio: "./audio/wonbuk/06/try.mp3", english: "try", korean: "노력하다, 시도하다", example: "Try your best to win." },
    { id: "wonbuk-06", image: "./img/wonbuk/06/use.png", audio: "./audio/wonbuk/06/use.mp3", english: "use", korean: "이용하다, 쓰다", example: "You can use my phone." },
    { id: "wonbuk-06", image: "./img/wonbuk/06/speak.png", audio: "./audio/wonbuk/06/speak.mp3", english: "speak", korean: "말하다, 이야기하다", example: "Please speak slowly." },
    { id: "wonbuk-06", image: "./img/wonbuk/06/cook.png", audio: "./audio/wonbuk/06/cook.mp3", english: "cook", korean: "요리하다", example: "I like to cook pasta." },
    { id: "wonbuk-06", image: "./img/wonbuk/06/knife.png", audio: "./audio/wonbuk/06/knife.mp3", english: "knife", korean: "칼, 나이프", example: "Be careful with the knife." },
    { id: "wonbuk-06", image: "./img/wonbuk/06/elephant.png", audio: "./audio/wonbuk/06/elephant.mp3", english: "elephant", korean: "코끼리", example: "The elephant is very big." },
    { id: "wonbuk-06", image: "./img/wonbuk/06/elevator.png", audio: "./audio/wonbuk/06/elevator.mp3", english: "elevator", korean: "엘리베이터", example: "Let’s take the elevator." },
    { id: "wonbuk-07", image: "./img/wonbuk/07/excuse.png", audio: "./audio/wonbuk/07/excuse.mp3", english: "excuse", korean: "변명, 핑계", example: "That is just an excuse." },
    { id: "wonbuk-07", image: "./img/wonbuk/07/idea.png", audio: "./audio/wonbuk/07/idea.mp3", english: "idea", korean: "생각, 아이디어", example: "I have a good idea." },
    { id: "wonbuk-07", image: "./img/wonbuk/07/left.png", audio: "./audio/wonbuk/07/left.mp3", english: "left", korean: "왼쪽", example: "Turn left at the corner." },
    { id: "wonbuk-07", image: "./img/wonbuk/07/picnic.png", audio: "./audio/wonbuk/07/picnic.mp3", english: "picnic", korean: "소풍, 피크닉", example: "We had a picnic in the park." },
    { id: "wonbuk-07", image: "./img/wonbuk/07/rock.png", audio: "./audio/wonbuk/07/rock.mp3", english: "rock", korean: "바위, 돌, 암석", example: "He is sitting on a big rock." },
    { id: "wonbuk-07", image: "./img/wonbuk/07/sky.png", audio: "./audio/wonbuk/07/sky.mp3", english: "sky", korean: "하늘, 상공", example: "The sky is very blue today." },
    { id: "wonbuk-07", image: "./img/wonbuk/07/tower.png", audio: "./audio/wonbuk/07/tower.mp3", english: "tower", korean: "타워, 탑, 고층 빌딩", example: "The tower is very tall." },
    { id: "wonbuk-07", image: "./img/wonbuk/07/where.png", audio: "./audio/wonbuk/07/where.mp3", english: "where", korean: "어디, 장소", example: "Where is my bag?" },
    { id: "wonbuk-07", image: "./img/wonbuk/07/church.png", audio: "./audio/wonbuk/07/church.mp3", english: "church", korean: "교회, 성당", example: "We go to church on Sundays." },
    { id: "wonbuk-07", image: "./img/wonbuk/07/ear.png", audio: "./audio/wonbuk/07/ear.mp3", english: "ear", korean: "귀, 청각", example: "My ear hurts." },
    { id: "wonbuk-08", image: "./img/wonbuk/08/glass.png", audio: "./audio/wonbuk/08/glass.mp3", english: "glass", korean: "유리, 잔", example: "The glass is full of water." },
    { id: "wonbuk-08", image: "./img/wonbuk/08/hair.png", audio: "./audio/wonbuk/08/hair.mp3", english: "hair", korean: "머리카락", example: "Her hair is very long." },
    { id: "wonbuk-08", image: "./img/wonbuk/08/homework.png", audio: "./audio/wonbuk/08/homework.mp3", english: "homework", korean: "숙제", example: "I finished my homework." },
    { id: "wonbuk-08", image: "./img/wonbuk/08/hospital.png", audio: "./audio/wonbuk/08/hospital.mp3", english: "hospital", korean: "병원", example: "He is in the hospital." },
    { id: "wonbuk-08", image: "./img/wonbuk/08/night.png", audio: "./audio/wonbuk/08/night.mp3", english: "night", korean: "밤, 야간, 어둠", example: "The stars shine at night." },
    { id: "wonbuk-08", image: "./img/wonbuk/08/problem.png", audio: "./audio/wonbuk/08/problem.mp3", english: "problem", korean: "문제, 과제", example: "This is a big problem." },
    { id: "wonbuk-08", image: "./img/wonbuk/08/singer.png", audio: "./audio/wonbuk/08/singer.mp3", english: "singer", korean: "가수, 싱어", example: "She is a famous singer." },
    { id: "wonbuk-08", image: "./img/wonbuk/08/room.png", audio: "./audio/wonbuk/08/room.mp3", english: "room", korean: "방, 공간", example: "My room is clean." },
    { id: "wonbuk-08", image: "./img/wonbuk/08/spoon.png", audio: "./audio/wonbuk/08/spoon.mp3", english: "spoon", korean: "숟가락, 스푼", example: "Please give me a spoon." },
    { id: "wonbuk-08", image: "./img/wonbuk/08/job.png", audio: "./audio/wonbuk/08/job.mp3", english: "job", korean: "직업, 일자리", example: "He got a new job." },
    { id: "wonbuk-09", image: "./img/wonbuk/09/movie.png", audio: "./audio/wonbuk/09/movie.mp3", english: "movie", korean: "영화, 무비", example: "I watched a funny movie." },
    { id: "wonbuk-09", image: "./img/wonbuk/09/park.png", audio: "./audio/wonbuk/09/park.mp3", english: "park", korean: "공원, 주차하다", example: "Let’s go to the park." },
    { id: "wonbuk-09", image: "./img/wonbuk/09/potato.png", audio: "./audio/wonbuk/09/potato.mp3", english: "potato", korean: "감자, 포테이토", example: "I like fried potatoes." },
    { id: "wonbuk-09", image: "./img/wonbuk/09/river.png", audio: "./audio/wonbuk/09/river.mp3", english: "river", korean: "강, 하천", example: "The river is very wide." },
    { id: "wonbuk-09", image: "./img/wonbuk/09/then.png", audio: "./audio/wonbuk/09/then.mp3", english: "then", korean: "그 때, 그 다음에, 그 당시에", example: "I was very happy then." },
    { id: "wonbuk-09", image: "./img/wonbuk/09/love.png", audio: "./audio/wonbuk/09/love.mp3", english: "love", korean: "사랑하다, 좋아하다", example: "I love my family." },
    { id: "wonbuk-09", image: "./img/wonbuk/09/hurry.png", audio: "./audio/wonbuk/09/hurry.mp3", english: "hurry", korean: "서두르다, 급하다", example: "Hurry, we are late!" },
    { id: "wonbuk-09", image: "./img/wonbuk/09/back.png", audio: "./audio/wonbuk/09/back.mp3", english: "back", korean: "돌아가다, 뒤, 등", example: "Please come back soon." },
    { id: "wonbuk-09", image: "./img/wonbuk/09/study.png", audio: "./audio/wonbuk/09/study.mp3", english: "study", korean: "공부, 연구", example: "I study English every day." },
    { id: "wonbuk-09", image: "./img/wonbuk/09/lesson.png", audio: "./audio/wonbuk/09/lesson.mp3", english: "lesson", korean: "수업, 단원, 교훈", example: "Today’s lesson is about animals." },
    { id: "wonbuk-10", image: "./img/wonbuk/10/paper.png", audio: "./audio/wonbuk/10/paper.mp3", english: "paper", korean: "종이, 신문, 서류", example: "I need a piece of paper." },
    { id: "wonbuk-10", image: "./img/wonbuk/10/scissors.png", audio: "./audio/wonbuk/10/scissors.mp3", english: "scissors", korean: "가위", example: "Please cut it with the scissors." },
    { id: "wonbuk-10", image: "./img/wonbuk/10/sock.png", audio: "./audio/wonbuk/10/sock.mp3", english: "sock", korean: "양말", example: "I lost one sock." },
    { id: "wonbuk-10", image: "./img/wonbuk/10/sound.png", audio: "./audio/wonbuk/10/sound.mp3", english: "sound", korean: "소리, 들리다, 사운드", example: "I hear a strange sound." },
    { id: "wonbuk-10", image: "./img/wonbuk/10/uncle.png", audio: "./audio/wonbuk/10/uncle.mp3", english: "uncle", korean: "삼촌, 아저씨", example: "My uncle lives in Busan." },
    { id: "wonbuk-10", image: "./img/wonbuk/10/camping.png", audio: "./audio/wonbuk/10/camping.mp3", english: "camping", korean: "캠핑, 야영", example: "We went camping last weekend." },
    { id: "wonbuk-10", image: "./img/wonbuk/10/backyard.png", audio: "./audio/wonbuk/10/backyard.mp3", english: "backyard", korean: "뒷마당, 뒤뜰", example: "There is a tree in the backyard." },
    { id: "wonbuk-10", image: "./img/wonbuk/10/bathroom.png", audio: "./audio/wonbuk/10/bathroom.mp3", english: "bathroom", korean: "화장실, 욕실", example: "The bathroom is clean." },
    { id: "wonbuk-10", image: "./img/wonbuk/10/bedroom.png", audio: "./audio/wonbuk/10/bedroom.mp3", english: "bedroom", korean: "침실", example: "My bedroom is small but cozy." },
    { id: "wonbuk-10", image: "./img/wonbuk/10/cousin.png", audio: "./audio/wonbuk/10/cousin.mp3", english: "cousin", korean: "사촌, 친척", example: "My cousin is the same age as me." },
    { id: "wonbuk-11", image: "./img/wonbuk/11/dish.png", audio: "./audio/wonbuk/11/dish.mp3", english: "dish", korean: "접시, 요리", example: "Wash the dirty dishes." },
    { id: "wonbuk-11", image: "./img/wonbuk/11/fork.png", audio: "./audio/wonbuk/11/fork.mp3", english: "fork", korean: "포크", example: "Please use a fork to eat pasta." },
    { id: "wonbuk-11", image: "./img/wonbuk/11/future.png", audio: "./audio/wonbuk/11/future.mp3", english: "future", korean: "미래, 장래", example: "I want to be a doctor in the future." },
    { id: "wonbuk-11", image: "./img/wonbuk/11/house.png", audio: "./audio/wonbuk/11/house.mp3", english: "house", korean: "집, 주택", example: "Our house is very big." },
    { id: "wonbuk-11", image: "./img/wonbuk/11/holiday.png", audio: "./audio/wonbuk/11/holiday.mp3", english: "holiday", korean: "휴일, 공휴일, 휴가", example: "We are going to the beach for the holiday." },
    { id: "wonbuk-11", image: "./img/wonbuk/11/people.png", audio: "./audio/wonbuk/11/people.mp3", english: "people", korean: "사람들, 국민", example: "Many people are at the festival." },
    { id: "wonbuk-11", image: "./img/wonbuk/11/zoo.png", audio: "./audio/wonbuk/11/zoo.mp3", english: "zoo", korean: "동물원", example: "Let’s visit the zoo this weekend." },
    { id: "wonbuk-11", image: "./img/wonbuk/11/kitchen.png", audio: "./audio/wonbuk/11/kitchen.mp3", english: "kitchen", korean: "부엌, 주방", example: "Mom is cooking in the kitchen." },
    { id: "wonbuk-11", image: "./img/wonbuk/11/must.png", audio: "./audio/wonbuk/11/must.mp3", english: "must", korean: "~해야 한다, 꼭 ~해야 한다", example: "You must wear a seatbelt." },
    { id: "wonbuk-11", image: "./img/wonbuk/11/buy.png", audio: "./audio/wonbuk/11/buy.mp3", english: "buy", korean: "사다, 구입하다", example: "I want to buy a new phone." },
    { id: "wonbuk-12", image: "./img/wonbuk/12/join.png", audio: "./audio/wonbuk/12/join.mp3", english: "join", korean: "참여하다, 가입하다", example: "I want to join the club." },
    { id: "wonbuk-12", image: "./img/wonbuk/12/listen.png", audio: "./audio/wonbuk/12/listen.mp3", english: "listen", korean: "듣다, 귀를 기울이다", example: "Please listen to the teacher." },
    { id: "wonbuk-12", image: "./img/wonbuk/12/visit.png", audio: "./audio/wonbuk/12/visit.mp3", english: "visit", korean: "방문하다", example: "We will visit grandma this weekend." },
    { id: "wonbuk-12", image: "./img/wonbuk/12/get.png", audio: "./audio/wonbuk/12/get.mp3", english: "get", korean: "얻다, 받다, 가지다", example: "I will get a new book." },
    { id: "wonbuk-12", image: "./img/wonbuk/12/miss.png", audio: "./audio/wonbuk/12/miss.mp3", english: "miss", korean: "놓치다, 그리워하다", example: "Don’t miss the bus." },
    { id: "wonbuk-12", image: "./img/wonbuk/12/turn.png", audio: "./audio/wonbuk/12/turn.mp3", english: "turn", korean: "돌리다, 바꾸다, 전환하다", example: "Turn the page, please." },
    { id: "wonbuk-12", image: "./img/wonbuk/12/enjoy.png", audio: "./audio/wonbuk/12/enjoy.mp3", english: "enjoy", korean: "즐기다", example: "Enjoy your meal." },
    { id: "wonbuk-12", image: "./img/wonbuk/12/kick.png", audio: "./audio/wonbuk/12/kick.mp3", english: "kick", korean: "차다", example: "He can kick the ball very far." },
    { id: "wonbuk-12", image: "./img/wonbuk/12/think.png", audio: "./audio/wonbuk/12/think.mp3", english: "think", korean: "생각하다, 상상하다", example: "I think you are right." },
    { id: "wonbuk-12", image: "./img/wonbuk/12/museum.png", audio: "./audio/wonbuk/12/museum.mp3", english: "museum", korean: "박물관, 미술관", example: "We saw many paintings at the museum." }
];
