const words = [
    { id: "0001", image: "./img/0001/blob.png", english: "blob", korean: "(걸쭉한 액체의) 방울", example: "Here come the blobs!" },
    { id: "0001", image: "./img/0001/gift.png", english: "gift", korean: "선물", example: "They see a gift shop." },
    { id: "0001", image: "./img/0001/shop.png", english: "shop", korean: "상점, 가게", example: "They see a gift shop." },
    { id: "0001", image: "./img/0001/gift_shop.png", english: "gift shop", korean: "선물 가게", example: "They see a gift shop." },
    { id: "0001", image: "./img/0001/come.png", english: "come", korean: "(…쪽으로) 오다", example: "Here come the blobs!" },
    { id: "0001", image: "./img/0001/see.png", english: "see", korean: "보다", example: "What do they see?" },
    { id: "0001", image: "./img/0001/inside.png", english: "inside", korean: "안에, 안쪽에, 안으로", example: "The blobs go inside." },
    { id: "0001", image: "./img/0001/get.png", english: "get", korean: "가지다, 받다, 얻다", example: "They get four T-shirts." },
    { id: "0001", image: "./img/0001/tshirt.png", english: "T-shirt", korean: "티셔츠", example: "They get four T-shirts." },
    { id: "0001", image: "./img/0001/cap.png", english: "cap", korean: "모자, 캡", example: "They get four caps." },
    { id: "0001", image: "./img/0001/balloon.png", english: "balloon", korean: "풍선", example: "They get four balloons." },
    { id: "0001", image: "./img/0001/cup.png", english: "cup", korean: "컵", example: "They get four cups." },
    { id: "0001", image: "./img/0001/bag.png", english: "bag", korean: "가방, 봉지", example: "They get four bags." },
    { id: "0001", image: "./img/0001/only.png", english: "only", korean: "단지, 오직", example: "But there are only three blobs." },
    { id: "0001", image: "./img/0001/teddy_bear.png", english: "teddy bear", korean: "테디 베어, 곰 인형", example: "They get a teddy bear!" },
    { id: "0001", image: "./img/0001/take_a_picture.png", english: "take a picture", korean: "사진을 찍다", example: "They take a picture!" },
    { id: "0001", image: "./img/0001/silly.png", english: "silly", korean: "우스꽝스러운, 유치한", example: "Silly blobs!" },
    { id: "0001", image: "./img/0001/good_bye.png", english: "good-bye", korean: "안녕, 안녕히 계세요 (헤어질 때 하는 인사)", example: "Good-bye!" },
    { id: "0001", image: "./img/0001/click.png", english: "Click!", korean: "(찰칵) 사진 찍는 소리", example: "Click! They take a picture!" },
    { id: "0001", image: "./img/0001/picture.png", english: "picture", korean: "사진, 그림", example: "They take a picture!" },
    { id: "0002", image: "./img/0002/blob.png", english: "blob", korean: "(걸쭉한 액체의) 방울·덩어리", example: "Here come the blobs!" },
    { id: "0002", image: "./img/0002/bumper.png", english: "bumper", korean: "(자동차의) 범퍼", example: "They see bumper cars!" },
    { id: "0002", image: "./img/0002/bumper_car.png", english: "bumper car", korean: "범퍼카(놀이기구)", example: "They see bumper cars!" },
    { id: "0002", image: "./img/0002/get_into.png", english: "get into", korean: "…에 들어가다, 타다", example: "The blobs get into a car." },
    { id: "0002", image: "./img/0002/forward.png", english: "forward", korean: "앞으로", example: "The bumper car goes forward." },
    { id: "0002", image: "./img/0002/bump.png", english: "bump", korean: "쿵! (부딪치는 소리)", example: "Bump!" },
    { id: "0002", image: "./img/0002/backward.png", english: "backward", korean: "뒤로", example: "The car goes backward." },
    { id: "0002", image: "./img/0002/left.png", english: "left", korean: "왼쪽으로", example: "The car goes left." },
    { id: "0002", image: "./img/0002/right.png", english: "right", korean: "오른쪽으로", example: "The car goes right." },
    { id: "0002", image: "./img/0002/slow.png", english: "slow", korean: "느리게", example: "The car goes slow." },
    { id: "0002", image: "./img/0002/fast.png", english: "fast", korean: "빠르게", example: "The car goes fast." },
    { id: "0002", image: "./img/0002/really.png", english: "really", korean: "정말로", example: "The car goes really fast!" },
    { id: "0002", image: "./img/0002/vroom.png", english: "Vroom!", korean: "부르릉!", example: "Vroom!" },
    { id: "0002", image: "./img/0002/silly.png", english: "silly", korean: "우스꽝스러운, 유치한", example: "Silly!" },
    { id: "0002", image: "./img/0002/car.png", english: "car", korean: "자동차", example: "The blobs get into a car." }
];