const words = [
    { id: "FS0127-01", image: "./img/FS0127/01/blob.png", audio: "./audio/FS0127/01/blob.mp3", english: "blob", korean: "(걸쭉한 액체의) 방울", example: "Here come the blobs!" },
    { id: "FS0127-01", image: "./img/FS0127/01/gift.png", audio: "./audio/FS0127/01/gift.mp3", english: "gift", korean: "선물", example: "They see a gift shop." },
    { id: "FS0127-01", image: "./img/FS0127/01/shop.png", audio: "./audio/FS0127/01/shop.mp3", english: "shop", korean: "상점, 가게", example: "They see a gift shop." },
    { id: "FS0127-01", image: "./img/FS0127/01/gift_shop.png", audio: "./audio/FS0127/01/gift_shop.mp3", english: "gift shop", korean: "선물 가게", example: "They see a gift shop." },
    { id: "FS0127-01", image: "./img/FS0127/01/come.png", audio: "./audio/FS0127/01/come.mp3", english: "come", korean: "(…쪽으로) 오다", example: "Here come the blobs!" },
    { id: "FS0127-01", image: "./img/FS0127/01/see.png", audio: "./audio/FS0127/01/see.mp3", english: "see", korean: "보다", example: "What do they see?" },
    { id: "FS0127-01", image: "./img/FS0127/01/inside.png", audio: "./audio/FS0127/01/inside.mp3", english: "inside", korean: "안에, 안쪽에, 안으로", example: "The blobs go inside." },
    { id: "FS0127-01", image: "./img/FS0127/01/get.png", audio: "./audio/FS0127/01/get.mp3", english: "get", korean: "가지다, 받다, 얻다", example: "They get four T-shirts." },
    { id: "FS0127-01", image: "./img/FS0127/01/tshirt.png", audio: "./audio/FS0127/01/tshirt.mp3", english: "T-shirt", korean: "티셔츠", example: "They get four T-shirts." },
    { id: "FS0127-01", image: "./img/FS0127/01/cap.png", audio: "./audio/FS0127/01/cap.mp3", english: "cap", korean: "모자, 캡", example: "They get four caps." },
    { id: "FS0127-01", image: "./img/FS0127/01/balloon.png", audio: "./audio/FS0127/01/balloon.mp3", english: "balloon", korean: "풍선", example: "They get four balloons." },
    { id: "FS0127-01", image: "./img/FS0127/01/cup.png", audio: "./audio/FS0127/01/cup.mp3", english: "cup", korean: "컵", example: "They get four cups." },
    { id: "FS0127-01", image: "./img/FS0127/01/bag.png", audio: "./audio/FS0127/01/bag.mp3", english: "bag", korean: "가방, 봉지", example: "They get four bags." },
    { id: "FS0127-01", image: "./img/FS0127/01/only.png", audio: "./audio/FS0127/01/only.mp3", english: "only", korean: "단지, 오직", example: "But there are only three blobs." },
    { id: "FS0127-01", image: "./img/FS0127/01/teddy_bear.png", audio: "./audio/FS0127/01/teddy_bear.mp3", english: "teddy bear", korean: "테디 베어, 곰 인형", example: "They get a teddy bear!" },
    { id: "FS0127-01", image: "./img/FS0127/01/take_a_picture.png", audio: "./audio/FS0127/01/take_a_picture.mp3", english: "take a picture", korean: "사진을 찍다", example: "They take a picture!" },
    { id: "FS0127-01", image: "./img/FS0127/01/silly.png", audio: "./audio/FS0127/01/silly.mp3", english: "silly", korean: "우스꽝스러운, 유치한", example: "Silly blobs!" },
    { id: "FS0127-01", image: "./img/FS0127/01/good_bye.png", audio: "./audio/FS0127/01/good_bye.mp3", english: "good-bye", korean: "안녕, 안녕히 계세요 (헤어질 때 하는 인사)", example: "Good-bye!" },
    { id: "FS0127-01", image: "./img/FS0127/01/click.png", audio: "./audio/FS0127/01/click.mp3", english: "Click!", korean: "(찰칵) 사진 찍는 소리", example: "Click! They take a picture!" },
    { id: "FS0127-01", image: "./img/FS0127/01/picture.png", audio: "./audio/FS0127/01/picture.mp3", english: "picture", korean: "사진, 그림", example: "They take a picture!" },
    { id: "FS0127-02", image: "./img/FS0127/02/blob.png", audio: "./audio/FS0127/02/blob.mp3", english: "blob", korean: "(걸쭉한 액체의) 방울·덩어리", example: "Here come the blobs!" },
    { id: "FS0127-02", image: "./img/FS0127/02/bumper.png", audio: "./audio/FS0127/02/bumper.mp3", english: "bumper", korean: "(자동차의) 범퍼", example: "They see bumper cars!" },
    { id: "FS0127-02", image: "./img/FS0127/02/bumper_car.png", audio: "./audio/FS0127/02/bumper_car.mp3", english: "bumper car", korean: "범퍼카(놀이기구)", example: "They see bumper cars!" },
    { id: "FS0127-02", image: "./img/FS0127/02/get_into.png", audio: "./audio/FS0127/02/get_into.mp3", english: "get into", korean: "…에 들어가다, 타다", example: "The blobs get into a car." },
    { id: "FS0127-02", image: "./img/FS0127/02/forward.png", audio: "./audio/FS0127/02/forward.mp3", english: "forward", korean: "앞으로", example: "The bumper car goes forward." },
    { id: "FS0127-02", image: "./img/FS0127/02/bump.png", audio: "./audio/FS0127/02/bump.mp3", english: "bump", korean: "쿵! (부딪치는 소리)", example: "Bump!" },
    { id: "FS0127-02", image: "./img/FS0127/02/backward.png", audio: "./audio/FS0127/02/backward.mp3", english: "backward", korean: "뒤로", example: "The car goes backward." },
    { id: "FS0127-02", image: "./img/FS0127/02/left.png", audio: "./audio/FS0127/02/left.mp3", english: "left", korean: "왼쪽으로", example: "The car goes left." },
    { id: "FS0127-02", image: "./img/FS0127/02/right.png", audio: "./audio/FS0127/02/right.mp3", english: "right", korean: "오른쪽으로", example: "The car goes right." },
    { id: "FS0127-02", image: "./img/FS0127/02/slow.png", audio: "./audio/FS0127/02/slow.mp3", english: "slow", korean: "느리게", example: "The car goes slow." },
    { id: "FS0127-02", image: "./img/FS0127/02/fast.png", audio: "./audio/FS0127/02/fast.mp3", english: "fast", korean: "빠르게", example: "The car goes fast." },
    { id: "FS0127-02", image: "./img/FS0127/02/really.png", audio: "./audio/FS0127/02/really.mp3", english: "really", korean: "정말로", example: "The car goes really fast!" },
    { id: "FS0127-02", image: "./img/FS0127/02/vroom.png", audio: "./audio/FS0127/02/vroom.mp3", english: "Vroom!", korean: "부르릉!", example: "Vroom!" },
    { id: "FS0127-02", image: "./img/FS0127/02/silly.png", audio: "./audio/FS0127/02/silly.mp3", english: "silly", korean: "우스꽝스러운, 유치한", example: "Silly!" },
    { id: "FS0127-02", image: "./img/FS0127/02/car.png", audio: "./audio/FS0127/02/car.mp3", english: "car", korean: "자동차", example: "The blobs get into a car." },
    { id: "FS0127-03", image: "./img/FS0127/03/blob.png", audio: "./audio/FS0127/03/blob.mp3", english: "blob", korean: "(둥글한) 덩어리, 블롭", example: "Here come the blobs!" },
    { id: "FS0127-03", image: "./img/FS0127/03/merry_go_round.png", audio: "./audio/FS0127/03/merry_go_round.mp3", english: "merry-go-round", korean: "회전목마", example: "They see a merry-go-round!" },
    { id: "FS0127-03", image: "./img/FS0127/03/go_up_to.png", audio: "./audio/FS0127/03/go_up_to.mp3", english: "go up to", korean: "…에게/…쪽으로 다가가다", example: "The blobs go up to the merry-go-round." },
    { id: "FS0127-03", image: "./img/FS0127/03/horse.png", audio: "./audio/FS0127/03/horse.mp3", english: "horse", korean: "말", example: "There’s a horse." },
    { id: "FS0127-03", image: "./img/FS0127/03/donkey.png", audio: "./audio/FS0127/03/donkey.mp3", english: "donkey", korean: "당나귀", example: "There’s a donkey." },
    { id: "FS0127-03", image: "./img/FS0127/03/giraffe.png", audio: "./audio/FS0127/03/giraffe.mp3", english: "giraffe", korean: "기린", example: "There’s a giraffe." },
    { id: "FS0127-03", image: "./img/FS0127/03/zebra.png", audio: "./audio/FS0127/03/zebra.mp3", english: "zebra", korean: "얼룩말", example: "There’s a zebra." },
    { id: "FS0127-03", image: "./img/FS0127/03/elephant.png", audio: "./audio/FS0127/03/elephant.mp3", english: "elephant", korean: "코끼리", example: "There’s an elephant." },
    { id: "0003", image: "./img/FS0127/03/whats_wrong.png", audio: "./audio/FS0127/03/whats_wrong.mp3", english: "what’s wrong?", korean: "무슨 일이야? 왜 그래?", example: "Blobs, what’s wrong?" },
    { id: "FS0127-03", image: "./img/FS0127/03/scary.png", audio: "./audio/FS0127/03/scary.mp3", english: "scary", korean: "무서운", example: "There’s a scary lion!" },
    { id: "FS0127-03", image: "./img/FS0127/03/lion.png", audio: "./audio/FS0127/03/lion.mp3", english: "lion", korean: "사자", example: "There’s a scary lion!" },
    { id: "FS0127-03", image: "./img/FS0127/03/run.png", audio: "./audio/FS0127/03/run.mp3", english: "run", korean: "달리다", example: "The blobs run." },
    { id: "FS0127-03", image: "./img/FS0127/03/whew.png", audio: "./audio/FS0127/03/whew.mp3", english: "whew", korean: "휴~, 살았다", example: "Whew, the lion is gone." },
    { id: "FS0127-03", image: "./img/FS0127/03/gone.png", audio: "./audio/FS0127/03/gone.mp3", english: "gone", korean: "사라진, 없는", example: "The lion is gone." },
    { id: "FS0127-03", image: "./img/FS0127/03/back.png", audio: "./audio/FS0127/03/back.mp3", english: "back", korean: "돌아와서", example: "Oh no! The lion’s back!" },
    { id: "FS0127-03", image: "./img/FS0127/03/silly.png", audio: "./audio/FS0127/03/silly.mp3", english: "silly", korean: "우스꽝스러운, 유치한", example: "Silly blobs!" },


    { id: "wonbuk-01", image: "./img/wonbuk/01/clean.png", audio: "./audio/wonbuk/01/clean.mp3", english: "clean", korean: "깨끗한, 청소하다", example: "My room is clean." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/wonderful.png", audio: "./audio/wonbuk/01/wonderful.mp3", english: "wonderful", korean: "멋진, 훌륭한, 놀라운", example: "The cake is wonderful." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/home.png", audio: "./audio/wonbuk/01/home.mp3", english: "home", korean: "집, 가정", example: "I go home after school." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/angry.png", audio: "./audio/wonbuk/01/angry.mp3", english: "angry", korean: "화난, 성난", example: "He is angry." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/really.png", audio: "./audio/wonbuk/01/really.mp3", english: "really", korean: "정말, 사실상, 실제로", example: "I really like pizza." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/well.png", audio: "./audio/wonbuk/01/well.mp3", english: "well", korean: "잘, 충분히, 우물", example: "She swims well." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/middle.png", audio: "./audio/wonbuk/01/middle.mp3", english: "middle", korean: "중앙의, 중간의", example: "Put the ball in the middle." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/tall.png", audio: "./audio/wonbuk/01/tall.mp3", english: "tall", korean: "키가 큰, 높은", example: "The tree is tall." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/every.png", audio: "./audio/wonbuk/01/every.mp3", english: "every", korean: "모든, 모두", example: "I read every day." },
    { id: "wonbuk-01", image: "./img/wonbuk/01/long.png", audio: "./audio/wonbuk/01/long.mp3", english: "long", korean: "긴, 오래, 오랫동안", example: "The river is long." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/short.png", audio: "./audio/wonbuk/02/short.mp3", english: "short", korean: "짧은", example: "My hair is short." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/straight.png", audio: "./audio/wonbuk/02/straight.mp3", english: "straight", korean: "똑바른", example: "Draw a straight line." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/ahead.png", audio: "./audio/wonbuk/02/ahead.mp3", english: "ahead", korean: "앞에(로)", example: "Walk ahead." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/busy.png", audio: "./audio/wonbuk/02/busy.mp3", english: "busy", korean: "바쁜", example: "Dad is busy." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/full.png", audio: "./audio/wonbuk/02/full.mp3", english: "full", korean: "가득 찬", example: "The box is full." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/more.png", audio: "./audio/wonbuk/02/more.mp3", english: "more", korean: "더, 더 많이", example: "I want more juice." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/ready.png", audio: "./audio/wonbuk/02/ready.mp3", english: "ready", korean: "준비된", example: "Are you ready?" },
    { id: "wonbuk-02", image: "./img/wonbuk/02/some.png", audio: "./audio/wonbuk/02/some.mp3", english: "some", korean: "약간의, 몇몇", example: "I have some books." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/today.png", audio: "./audio/wonbuk/02/today.mp3", english: "today", korean: "오늘", example: "It is hot today." },
    { id: "wonbuk-02", image: "./img/wonbuk/02/favorite.png", audio: "./audio/wonbuk/02/favorite.mp3", english: "favorite", korean: "가장 좋아하는", example: "Pizza is my favorite food." }

];
